<?php

namespace AppBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByDate()
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery('
        SELECT p
        FROM AppBundle:Post p
        ORDER BY p.createdAt DESC
        ');

        return $query->getResult();
    }

    public function findByYear($year)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery('
        SELECT p
        FROM AppBundle:Post p
        WHERE YEAR(p.createdAt) = :year 
        ');

        $query->setParameter('year', $year);
        return $query->getResult();
    }
}
