<?php

namespace AppBundle\Repository;

/**
 * ReportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReportRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByYear($year)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery('
        SELECT r
        FROM AppBundle:Report r
        WHERE YEAR(r.date) = :year 
        ');

        $query->setParameter('year', $year);
        return $query->getResult();
    }
}
