<?php

namespace AppBundle\Repository;

/**
 * reportCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class reportCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
